inherit_gem:
  rubocop-config-umbrellio: lib/rubocop.yml

AllCops:
  DisplayCopNames: true
  TargetRubyVersion: 3.2

Naming/MethodParameterName:
  AllowedNames: ["x", "y", "z"]

RSpec/EmptyLineAfterHook:
  Enabled: false
